version: 2

sources:
  - name: staging
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: product_hunt

    tables:
      - name: product_hunt_products_materialized
      - name: product_category_materialized
