base:
  outputs:
    dev:
      type: duckdb
  target: dev
producthunt_dbt:
  outputs:
    dev:
      dataset: dbt_producthunt_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      type: bigquery
  target: dev
